name: carnd
channels:
#    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python>=3.6.2
    - numpy>=1.13.1
    - matplotlib>=2.0.2
    - jupyter>=1.0.0
    - opencv>=3.1.0
    - pillow
    - scikit-learn>=0.19.0
    - scikit-image
    - scipy>=0.19.1
    - h5py>=2.7.0
    - flask-socketio
    - seaborn
    - pandas>=0.20.3
    - ffmpeg
    - imageio
    - pyqt>=5.6.0
    - tensorflow>=1.3.0
    - mkl>=2017.0.3
    - nose
    - pip>=9.0.1
    - pip:
        - eventlet
        - pandas_ml
        - moviepy
        - keras>=2.0.8
